### PR TITLE
Localize readme

### PR DESCRIPTION
**Pull request by dfcreative**
Hi @acterhd!
So here is mostly localized readme, as you asked.
Enjoy!

### CODE REVIEW

**Comment by acterhd** [comment]
fix Please again 
both diagram is hcg

**Comment by dfcreative** [comment]
You’ve merged it already, you can fix it now by yourself ;)

**Comment by acterhd** [comment]
my email: acterhd@gmail.com
contact with me.

**Comment by dfcreative** [comment]
But actally no, first diagram is not HCG. At least, it does not correspond to the color picker in that case, and  it has no difference with HSL also.

**Comment by acterhd** [comment]
Diagrams have different orientations.

**Comment by dfcreative** [comment]
Ok, I don’t understand the sense of the first image then, but nevermind.

Also I’d recomment to change the picture with values for the colors, now the colors are senseless, it is better to describe the popular (easy to understand) ones: white/gray/black, pures: red, blue, cyan, pink, yellow, orange, green, darkgreen etc.

Also you should add "main" to the `package.json`.

Also it’s worth adding some examples of use to the readme.

**Comment by acterhd** [comment]
Okay, I try add additional table.

2016-02-03 6:10 GMT+08:00 Δॐma Yvanow <notifications@github.com>:

**Comment by acterhd** [comment]
added easy colors

**Comment by dfcreative** [comment]
:+1:

**Comment by acterhd** [comment]
Кстати, елочка на месте альтернативной диаграмма HGC (HCG). Сделано не случайно.

**Comment by dfcreative** [comment]
Новая диаграмма понятнее. Здорово.

**Comment by acterhd** [comment]
Чудеса Python, который дарит нам диаграммы и лаги.

**Pull request merged**
